[package]
name = "mdn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.5.2"
lazy_static = "1.4.0"
open = "3.2.0"
